import { DatagenReturnData } from "../../../lib";
import { DocModule } from "../../lib/DocModule";
import { DocFunction } from "../../lib/DocFunction";

const MathDocs = new DocModule("Math Functions", "", [
    new DocFunction("floor", "Rounds down to the nearest integer.",
        [{ name: "n", type: "number", description: "Value to round down" }], "number", "floor(3.9); // 3"),
    new DocFunction("ceil", "Rounds up to the nearest integer.",
        [{ name: "n", type: "number", description: "Value to round up" }], "number", "ceil(3.1); // 4"),
    new DocFunction("round", "Rounds to the nearest integer.",
        [{ name: "n", type: "number", description: "Value to round" }], "number", "round(3.6); // 4"),
    new DocFunction("abs", "Returns the absolute value.",
        [{ name: "n", type: "number", description: "Input value" }], "number", "abs(-5); // 5"),
    new DocFunction("sign", "Returns the sign of a number.",
        [{ name: "n", type: "number", description: "Input value" }], "number", "sign(-50); // -1"),
    new DocFunction("min", "Returns the smaller of two values.",
        [{ name: "a", type: "number", description: "First value" }, { name: "b", type: "number", description: "Second value" }], "number", "min(10, 5); // 5"),
    new DocFunction("max", "Returns the larger of two values.",
        [{ name: "a", type: "number", description: "First value" }, { name: "b", type: "number", description: "Second value" }], "number", "max(10, 5); // 10"),
    new DocFunction("clamp", "Constrains a value between min and max.",
        [{ name: "val", type: "number", description: "Value to constrain" }, { name: "min", type: "number", description: "Minimum bound" }, { name: "max", type: "number", description: "Maximum bound" }], "number", "clamp(15, 0, 10); // 10"),
    new DocFunction("lerp", "Linearly interpolates between two values.",
        [{ name: "a", type: "number", description: "Start value" }, { name: "b", type: "number", description: "End value" }, { name: "t", type: "number", description: "Interpolation factor (0-1)" }], "number", "lerp(0, 100, 0.5); // 50"),
    new DocFunction("power", "Returns base raised to the power of exp.",
        [{ name: "base", type: "number", description: "The base" }, { name: "exp", type: "number", description: "The exponent" }], "number", "power(2, 3); // 8"),
    new DocFunction("sqrt", "Returns the square root.",
        [{ name: "n", type: "number", description: "Value (must be >= 0)" }], "number", "sqrt(16); // 4"),
    new DocFunction("sqr", "Returns the square of a number.",
        [{ name: "n", type: "number", description: "Value to square" }], "number", "sqr(5); // 25"),
    new DocFunction("frac", "Returns the fractional part of a number.",
        [{ name: "n", type: "number", description: "Input value" }], "number", "frac(3.75); // 0.75"),
    new DocFunction("sin", "Returns sine of x in radians.",
        [{ name: "x", type: "number", description: "Angle in radians" }], "number"),
    new DocFunction("cos", "Returns cosine of x in radians.",
        [{ name: "x", type: "number", description: "Angle in radians" }], "number"),
    new DocFunction("tan", "Returns tangent of x in radians.",
        [{ name: "x", type: "number", description: "Angle in radians" }], "number"),
    new DocFunction("dsin", "Returns sine of x in degrees.",
        [{ name: "x", type: "number", description: "Angle in degrees" }], "number"),
    new DocFunction("dcos", "Returns cosine of x in degrees.",
        [{ name: "x", type: "number", description: "Angle in degrees" }], "number"),
    new DocFunction("dtan", "Returns tangent of x in degrees.",
        [{ name: "x", type: "number", description: "Angle in degrees" }], "number"),
    new DocFunction("degtorad", "Converts degrees to radians.",
        [{ name: "deg", type: "number", description: "Degrees" }], "number"),
    new DocFunction("radtodeg", "Converts radians to degrees.",
        [{ name: "rad", type: "number", description: "Radians" }], "number"),
    new DocFunction("lengthdir_x", "Returns the horizontal component of a vector.",
        [{ name: "len", type: "number", description: "Vector length" }, { name: "dir", type: "number", description: "Direction in degrees" }], "number"),
    new DocFunction("lengthdir_y", "Returns the vertical component of a vector.",
        [{ name: "len", type: "number", description: "Vector length" }, { name: "dir", type: "number", description: "Direction in degrees" }], "number"),
    new DocFunction("point_distance", "Returns the distance between two points.",
        [{ name: "x1", type: "number", description: "X of point 1" }, { name: "y1", type: "number", description: "Y of point 1" }, { name: "x2", type: "number", description: "X of point 2" }, { name: "y2", type: "number", description: "Y of point 2" }], "number"),
    new DocFunction("point_direction", "Returns the direction from point 1 to point 2.",
        [{ name: "x1", type: "number", description: "X of point 1" }, { name: "y1", type: "number", description: "Y of point 1" }, { name: "x2", type: "number", description: "X of point 2" }, { name: "y2", type: "number", description: "Y of point 2" }], "number"),
    new DocFunction("exp", "Returns e^n.",
        [{ name: "n", type: "number", description: "Exponent" }], "number"),
    new DocFunction("ln", "Returns the natural logarithm function of x.",
        [{ name: "x", type: "number", description: "Input value" }], "number"),
    new DocFunction("log2", "Returns the base-2 logarithm.",
        [{ name: "n", type: "number", description: "Input value" }], "number"),
    new DocFunction("log10", "Returns the base-10 logarithm.",
        [{ name: "n", type: "number", description: "Input value" }], "number"),
    new DocFunction("arcsin", "Returns the arcsine in radians.",
        [{ name: "x", type: "number", description: "Input value" }], "number"),
    new DocFunction("arccos", "Returns the arccosine in radians.",
        [{ name: "x", type: "number", description: "Input value" }], "number"),
    new DocFunction("arctan", "Returns the arctangent in radians.",
        [{ name: "x", type: "number", description: "Input value" }], "number"),
    new DocFunction("arctan2", "Returns the angle from origin to (x, y) in radians.",
        [{ name: "y", type: "number", description: "Y coordinate" }, { name: "x", type: "number", description: "X coordinate" }], "number"),
]);

export default [
    new DatagenReturnData("math.md", MathDocs.toMarkdown())
];
